import type { NextPage } from 'next';
import Head from 'next/head';
import HeaderBar from '../components/HeaderBar';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <>
    <HeaderBar />
    <div className={styles.container}>
      <Head>
        <title>Christian Oliveira - Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      </main>
    </div>
    </>
  )
}

export default Home
